name: LAMS

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - labeled

jobs:
  lams_job:
    runs-on: ubuntu-latest
    name: LAMS LookML Linter Job
    steps:
      - name: Checkout your LookML
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
