
name: LAMS fix

on: [push]

jobs:
  lams_job:
    runs-on: ubuntu-latest
    name: LAMS LookML Linter Job
    steps:
      - name: Checkout your LookML
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install LAMS
        run: npm install -g @looker/look-at-me-sideways@v3
        
      - name: Fetch master branch
        run: git fetch origin main
        
      # - name: Get Only Edited Files
      #   run: |
      #     mkdir -p lint_dir
      #     git diff --name-only --diff-filter=d origin/master | grep '\.lkml$' | xargs -I {} cp {} lint_dir
      #     cp manifest.lkml lint_dir
      #     ls -lrt lint_dir

      # - name: Run LAMS Over the Edited Files
      #   continue-on-error: true
      #   id: lams
      #   run: |
      #     lams --output-mode=lines --reporting=save-no --source='./lint_dir/{*.lkml,manifest.lkml}' | tee lams_output.txt
     
      - name: Auto-fix W1 indentation errors in changed files
        env:
          TOKEN: ${{ secrets.PAT_TOKEN_LOOKER_REPO }}
          GH_REPO: ${{ github.repository }}
        run: |
          chmod +x .github/action_scripts/lams_indent_fixer.sh
          .github/action_scripts/lams_indent_fixer.sh 
          
      - name: Commit changes
      - uses: EndBug/add-and-commit@v9
        with:
          add: |
            - afile.txt
            - anotherfile.txt

      - name: Install GitHub CLI
        run: sudo apt install gh

      - name: Add label to PR
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN_LOOKER_REPO }}
        run: |
          PR_NUMBER=$(gh pr list --head "$GITHUB_REF_NAME" --json number -q '.[0].number')
          echo "Found PR number: $PR_NUMBER"
          gh pr edit "$PR_NUMBER" --add-label "auto-fix"

